const relations = [
    "isogonal conjugate of",
    "isotomic conjugate of",
    "anticomplement of",
    "complement of",
    "anticomplementary conjugate of",
    "complementary conjugate of",
    "complementary conjugate at",
    "cyclocevian conjugate of",
    "polar conjugate of",
    "antigonal image of",
    "antitomic image of",
    "symgonal image of",

    // Inverse
    "circumcircle-inverse of",
    "incircle-inverse of",
    "Conway-circle-inverse of",
    "nine-point-circle-inverse of",
    "Brocard-circle-inverse of",
    "Fuhrmann-circle-inverse of",
    "Bevan-circle-inverse of",
    "Spieker-circle-inverse of",
    "Stevanovic-circle inverse of",
    "Spieker-radical-circle-inverse of",
    "orthocentroidal-circle-inverse of",
    "1st-Lemoine-circle-inverse of",
    "2nd-Lemoine-circle-inverse of",
    "Conway-circle-inverse of",
    "2nd-Brocard-circle-inverse of",
    "Grebe-circle-inverse of",
    "de-Longchamps-circle inverse of",
    "inner-Napoleon circle-inverse of",
    "outer-Napoleon circle-inverse of",

    // Triangle Conjugate
    "orthic-isogonal conjugate of",
    "excentral-isogonal conjugate of",
    "excentral-isotomic conjugate of",
    "hexyl-isogonal conjugate of",
];

const mapRelation = {
    "isogonal conjugate of": "isogonal conjugate",
    "isotomic conjugate of": "isotomic conjugate",
    "complement of": "complement",
    "anticomplement of": "anticomplement",
    "complementary conjugate of": "complementary conjugate",
    "cyclocevian conjugate of": "cyclocevian conjugate",
    "anticomplementary conjugate of": "anticomplementary conjugate",
    "complementary conjugate at": "complementary conjugate",
    "polar conjugate of": "polar conjugate",
    "antigonal image of": "antigonal image",
    "antitomic image of": "antitomic image",
    "symgonal image of": "symgonal image",

    // Inverse of circle
    "circumcircle-inverse of": "circumcircle inverse",
    "incircle-inverse of": "incircle inverse",
    "Conway-circle-inverse of": "Conway circle inverse",
    "nine-point-circle-inverse of": "nine point circle inverse",
    "Brocard-circle-inverse of": "Brocard circle inverse",
    "Fuhrmann-circle-inverse of": "Fuhrmann circle inverse",
    "Bevan-circle-inverse of": "Bevan circle inverse",
    "Spieker-circle-inverse of": "Spieker circle inverse",
    "Stevanovic-circle inverse of": "Stevanovic circle inverse",
    "Spieker-radical-circle-inverse of": "Spieker radical circle inverse",
    "orthocentroidal-circle-inverse of": "orthocentroidal circle inverse",
    "1st-Lemoine-circle-inverse of": "1st Lemoine circle inverse",
    "2nd-Lemoine-circle-inverse of": "2nd Lemoine circle inverse",
    "Conway-circle-inverse of": "Conway circle inverse",
    "2nd-Brocard-circle-inverse of": "2nd Brocard circle inverse",
    "Grebe-circle-inverse of": "Grebe circle inverse",
    "de-Longchamps-circle inverse of": "de Longchamps circle inverse",
    "inner-Napoleon circle-inverse of": "inner Napoleon circle inverse",
    "outer-Napoleon circle-inverse of": "outer Napoleon circle inverse",

    // Conjugate in triangle
    "orthic-isogonal conjugate of": "orthic isogonal conjugate",
    "excentral-isogonal conjugate of": "excentral isogonal conjugate",
    "excentral-isotomic conjugate of": "excentral isotomic conjugate",
    "hexyl-isogonal conjugate of": "hexyl isogonal conjugate",
};

export { relations, mapRelation };
